# Neokik Digital - Suspended Virtual Host Template
server {
    listen 80;
    listen [::]:80;
    server_name {{DOMAIN}} www.{{DOMAIN}};

    location / {
        root /var/www/neokik;
        try_files /suspended.html =503;
    }
}
